// #include <iostream>
// #include<algorithm>
// using namespace std;
// # define n 4
// void interchangeFirstLast(int arr[][n])
// {
//     // swapping of element between first
//     // and last columns
//     for (int i = 0; i < n; i++) {
//         int t = arr[i][0];
//         arr[i][0] = arr[i][n - 1];
//         arr[i][n - 1] = t;
//     }
// }

// int main(){
//     int arr1[4][4 ]={0};
//     int i,j;
//     for(i=0;i<2;i++){
//         for(j=0;j<3;j++){
//             cin>>arr1[i][j];
//         }
//     }
//         for(i=0;i<3;i++){
//             for(j=0;j<2;j++){
                
//                 cout<<arr1[j][i]<<" ";
                
//             }
//             cout<<endl;
            
//         }
//         interchangeFirstLast(arr1);
    
// return 0;
// }

